version: '3'

networks:
  envirosense-development:
    name: 'envirosense-development'

services:

  server:
    container_name: envirosense-app
    restart: always
    command: sh -c "npm run dev"
    build:
      context: ./server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - envirosense-development

  mongo:
    container_name: envirosense-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2023!
    ports:
      - "27017:27017"
    volumes:
      - /mongodb:/data/db
    networks:
      - envirosense-development
